name: linkbook-commons

on:
  push:
    branches:
      - main
jobs:
  buld-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v2
      - name: install and build
        run: npm ci
      - name: publish to registry
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@NibrasoftNet'
      - run: npm publish
