name: linkbook-commons

permissions: read-all

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout to repository
        uses: actions/checkout@v2
      - name: Update npm
        run: npx npm@10.2.4 install -g npm@8.19.4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install and build
        run: pnpm install --no-frozen-lockfile

      - name: publish to registry
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nibrasoftNet'

      - name: Publish to registry
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
